#For troubleshooting mongo we have this config so we can isolate just the mongo instance
version: '3.7'
services:

    mongo-dev: 
        container_name: mongo-dev 
        volumes:
            - '/home/clay/ferguson/mongodb-data-dev:/data/db'
            - '/home/clay/ferguson/mongo-dumps-dev:/mongo-dumps'
            - '/home/clay/ferguson/mongo-scripts-dev:/mongo-scripts'
            - '/home/clay/ferguson/mongo-conf-dev/mongod.conf:/etc/mongod.conf'
        #NOTE: This 'command' property is only needed when we want to start mongod on a port other than 27017    
        command: mongod --config /etc/mongod.conf
        #entrypoint: ["mongod","--config","/etc/mongod.conf"]
        ports:
            - '27016:27016'
        networks:
           - net-dev
        # Always specify version of mongo. When it upgrades automatically there can be database issues that need to be resolved
        # and we don't want that happening unexpectedly
        image: mongo:4

networks:
  net-dev:
    driver: bridge
    external: false
    name: net-dev

